/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiqRouteImport } from './routes/aiq'
import { Route as AskRouteImport } from './routes/ask'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MapsMapIdRouteImport } from './routes/maps.$mapId'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiqRoute = AiqRouteImport.update({
  id: '/aiq',
  path: '/aiq',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiq'
    | '/ask'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiq'
    | '/ask'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/aiq'
    | '/ask'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiqRoute: typeof AiqRoute
  AskRoute: typeof AskRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  SignupRoute: typeof SignupRoute
  WatchlistRoute: typeof WatchlistRoute
  MapsMapIdRoute: typeof MapsMapIdRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiq': {
      id: '/aiq'
      path: '/aiq'
      fullPath: '/aiq'
      preLoaderRoute: typeof AiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiqRoute: AiqRoute,
  AskRoute: AskRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRoute,
  SignupRoute: SignupRoute,
  WatchlistRoute: WatchlistRoute,
  MapsMapIdRoute: MapsMapIdRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
