/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiqRouteImport } from './routes/aiq'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MapsMapIdRouteImport } from './routes/maps.$mapId'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiqRoute = AiqRouteImport.update({
  id: '/aiq',
  path: '/aiq',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrganizationsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aiq': typeof AiqRoute
  '/ask': typeof AskRoute
  '/atlas': typeof AtlasRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/signup': typeof SignupRoute
  '/watchlist': typeof WatchlistRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aiq'
    | '/ask'
    | '/atlas'
    | '/billing'
    | '/dashboard'
    | '/graph'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/organizations/$orgId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aiq'
    | '/ask'
    | '/atlas'
    | '/billing'
    | '/dashboard'
    | '/graph'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/organizations/$orgId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aiq'
    | '/ask'
    | '/atlas'
    | '/billing'
    | '/dashboard'
    | '/graph'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/projects'
    | '/prompts'
    | '/signup'
    | '/watchlist'
    | '/maps/$mapId'
    | '/opportunities/$opportunityId'
    | '/organizations/$orgId'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiqRoute: typeof AiqRoute
  AskRoute: typeof AskRoute
  AtlasRoute: typeof AtlasRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  SignupRoute: typeof SignupRoute
  WatchlistRoute: typeof WatchlistRoute
  MapsMapIdRoute: typeof MapsMapIdRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiq': {
      id: '/aiq'
      path: '/aiq'
      fullPath: '/aiq'
      preLoaderRoute: typeof AiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiqRoute: AiqRoute,
  AskRoute: AskRoute,
  AtlasRoute: AtlasRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRoute,
  SignupRoute: SignupRoute,
  WatchlistRoute: WatchlistRoute,
  MapsMapIdRoute: MapsMapIdRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
